# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
        - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/sqlcon?sslmode=disable
        - TEST_DATABASE_MYSQL=root:test@(localhost:3306)/mysql?parseTime=true
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=sqlcon
      - image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=test
    working_directory: /go/src/github.com/ory/sqlcon
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: curl -L https://git.io/vp6lP | sh
      - run: mv ./bin/* $GOPATH/bin
      - run:
          name: Enable go1.11 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run: go mod download
      - run: gometalinter --disable-all --enable=goimports --enable=gosec --enable=dupl --enable=vet --enable=golint --vendor ./...
      - run: go test -race ./...
      - run: test -z "$CIRCLE_PR_NUMBER" && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"
