version: 2.1

orbs:
  nancy: ory/nancy@0.0.4

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
        - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/sqlcon?sslmode=disable
        - TEST_DATABASE_MYSQL=mysql://root:test@tcp(localhost:3306)/mysql?parseTime=true
        - TEST_DATABASE_COCKROACHDB=cockroach://root@localhost:26257/defaultdb?sslmode=disable
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=sqlcon
      - image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=test
      - image: cockroachdb/cockroach:v2.1.6
        command: start --insecure
    working_directory: /go/src/github.com/ory/sqlcon
    steps:
      - checkout
      - run: curl -L https://git.io/vp6lP | sh
      - run: mv ./bin/* $GOPATH/bin
      - run:
          name: Enable go1.11 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run: go mod download
      - run: make init
      - run: make lint
      - run: go-acc -o coverage.txt ./... -- -v
      - run: test -z "$CIRCLE_PR_NUMBER" && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"

  docs:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/oathkeeper
    steps:
      - checkout
      - run: git config --global user.email "hi@ory.sh"
      - run: git config --global user.name "ORY Continuous Integration"
      - run: "git clone https://arekkas:$DOCS_TOKEN_PUSH@github.com/ory/docs.git ../docs"
      - run: "mkdir -p ../docs/schemas/x; cp -r ./.schemas/* ../docs/schemas/x"
      - run: "(cd ../docs && git add -A && git commit -a -m \"Updates ory/x JSON Schemas\" && git push origin) || exit 0"

workflows:
  publish:
    jobs:
      - test
      - nancy/test
      - docs:
          filters:
            branches:
              only: master